In [2]:
!pip install python-dotenv

Requirement already satisfied: python-dotenv in c:\users\usuario\appdata\local\programs\python\python312\lib\site-packages (1.1.0)

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import os
import pandas as pd
import numpy as np
import psycopg2
from dotenv import load_dotenv

In [4]:
# Cargar las variables de entorno
load_dotenv()

#Obtener las variables
user = os.getenv("DB_USER")
password = os.getenv("DB_PASSWORD")
host = os.getenv("DB_HOST")
port = os.getenv("DB_PORT")
dbname = os.getenv("DB_NAME")

#Conectarse a la base de datos
conn = psycopg2.connect(
    dbname = dbname,
    user = user,
    password = password,
    host = host,
)

In [5]:
# Modificaciones a la tabla ciudad

# Creacion del cursor
cur = conn.cursor()

# Verificar si los cambios que se van a realizar han sido aplicados anteriormente (en caso de que no hayan sido aplicados se aplican automaticamente)

# ciudad_id -> id
cur.execute("""
    SELECT column_name
    FROM information_schema.columns
    WHERE table_name = 'ciudad'
    AND column_name = 'ciudad_id';
""")
result = cur.fetchone()

if result is not None:
    cur.execute("ALTER TABLE ciudad RENAME COLUMN ciudad_id TO id")

# nombre -> nombre_ciudad
cur.execute("""
    SELECT column_name
    FROM information_schema.columns
    WHERE table_name = 'ciudad'
    AND column_name = 'nombre';
""")
result = cur.fetchone()

if result is not None:
    cur.execute("ALTER TABLE ciudad RENAME COLUMN nombre TO nombre_ciudad")

# Confirmacion de los cambios
conn.commit()

# Cierre del cursor
cur.close()

query = ("SELECT * FROM ciudad;")
df = pd.read_sql(query, conn)
df

C:\Users\Usuario\AppData\Local\Temp\ipykernel_14468\2217929013.py:39: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

    id  nombre_ciudad  departamento_id
0    6           BUGA                1
1    5         BOGOTA                2
2    4          PASTO                4
3    3        POPAYAN                3
4    2        PALMIRA                1
5    1           CALI                1
6    7          TULUA                1
7   10        GUACARI                1
8   11     CANDELARIA                1
9   12        CARTAGO                1
10   9        JAMUNDI                1
11   8          YUMBO                1
12  13    ACOPI YUMBO                1
13  14   CENCAR YUMBO                1
14  15         ZARZAL                1
15  16     VILLA RICA                3
16  17        FLORIDA                1
17  18        PRADERA                1
18  19  CALIMA DARIEN                1

In [6]:
# Modificaciones a la tabla departamento

# Creacion del cursor
cur = conn.cursor()

# Verificar si los cambios que se van a realizar han sido aplicados anteriormente (en caso de que no hayan sido aplicados se aplican automaticamente)

# departamento_id -> id
cur.execute("""
    SELECT column_name
    FROM information_schema.columns
    WHERE table_name = 'departamento'
    AND column_name = 'departamento_id';
""")
result = cur.fetchone()

if result is not None:
    cur.execute("ALTER TABLE departamento RENAME COLUMN departamento_id TO id")

# nombre -> nombre_departamento
cur.execute("""
    SELECT column_name
    FROM information_schema.columns
    WHERE table_name = 'departamento'
    AND column_name = 'nombre';
""")
result = cur.fetchone()

if result is not None:
    cur.execute("ALTER TABLE departamento RENAME COLUMN nombre TO nombre_departamento")

# Confirmacion de los cambios
conn.commit()

# Cierre del cursor
cur.close()

query = ("SELECT * FROM departamento;")
df = pd.read_sql(query, conn)
df

C:\Users\Usuario\AppData\Local\Temp\ipykernel_14468\1456427408.py:39: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

   id nombre_departamento
0   4              NARIÑO
1   3               CAUCA
2   2        CUNDINAMARCA
3   1     VALLE DEL CAUCA

In [19]:
# Dimension cliente (dim_cliente)

# Creacion del cursor
cur = conn.cursor()

# Verificar si los cambios que se van a realizar han sido aplicados anteriormente (en caso de que no hayan sido aplicados se aplican automaticamente)

# cliente_id -> id
cur.execute("""
    SELECT column_name
    FROM information_schema.columns
    WHERE table_name = 'cliente'
    AND column_name = 'cliente_id'
""")
result = cur.fetchone()

if result is not None:
    cur.execute("ALTER TABLE cliente RENAME COLUMN cliente_id TO id")

# nombre -> nombre_cliente
cur.execute("""
    SELECT column_name
    FROM information_schema.columns
    WHERE table_name = 'cliente'
    AND column_name = 'nombre';
""")
result = cur.fetchone()

if result is not None:
    cur.execute("ALTER TABLE cliente RENAME COLUMN nombre TO nombre_cliente")

# Confirmacion de los cambios
conn.commit()

# Cierre del cursor
cur.close()

query = ("""
    SELECT cliente_id, nit_cliente, nombre_cliente, user_id, nombre_ciudad, nombre_departamento
    FROM clientes_usuarioaquitoy AS dim_cliente
    INNER JOIN ciudad ON dim_cliente.ciudad_id = ciudad.id
    INNER JOIN departamento ON ciudad.departamento_id = departamento.id
    INNER JOIN cliente ON dim_cliente.cliente_id = cliente.id
""")

df = pd.read_sql(query, conn)
df

C:\Users\Usuario\AppData\Local\Temp\ipykernel_32796\2340032141.py:46: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,cliente_id,nit_cliente,nombre_cliente,user_id,nombre_ciudad,nombre_departamento
0,11,327282-4,CARROS DEL PACIFICO (CHINA),166,CALI,VALLE DEL CAUCA
1,11,327282-4,CARROS DEL PACIFICO (CHINA),169,CALI,VALLE DEL CAUCA
2,11,327282-4,CARROS DEL PACIFICO (CHINA),168,CALI,VALLE DEL CAUCA
3,6,24390-3,CLINICA DEPORTIVA DEL SUR,176,CALI,VALLE DEL CAUCA
4,6,24390-3,CLINICA DEPORTIVA DEL SUR,171,CALI,VALLE DEL CAUCA
...,...,...,...,...,...,...
250,11,327282-4,CARROS DEL PACIFICO (CHINA),509,PASTO,NARIÑO
251,11,327282-4,CARROS DEL PACIFICO (CHINA),510,PASTO,NARIÑO
252,11,327282-4,CARROS DEL PACIFICO (CHINA),507,PASTO,NARIÑO
253,11,327282-4,CARROS DEL PACIFICO (CHINA),198,CALI,VALLE DEL CAUCA
254,11,327282-4,CARROS DEL PACIFICO (CHINA),511,CALI,VALLE DEL CAUCA

In [21]:
# Dimension mensajero (dim_mensajero)

# Creacion del cursor
cur = conn.cursor()

query = ("""
    SELECT dim_mensajero.id AS mensajero_id, username AS nombre, activo, fecha_entrada, nombre_ciudad AS ciudad_operacion, nombre_departamento AS departamento_operacion
    FROM clientes_mensajeroaquitoy AS dim_mensajero
    INNER JOIN auth_user ON dim_mensajero.user_id = auth_user.id
    LEFT JOIN ciudad ON dim_mensajero.ciudad_operacion_id = ciudad.id
    LEFT JOIN departamento ON ciudad.departamento_id = departamento.id
""")
df = pd.read_sql(query, conn)
df

C:\Users\Usuario\AppData\Local\Temp\ipykernel_32796\2122813142.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,mensajero_id,nombre,activo,fecha_entrada,ciudad_operacion,departamento_operacion
0,8,Luis Castro,True,2021-05-18,PALMIRA,VALLE DEL CAUCA
1,10,Luis Valenciano,True,2019-09-02,CALI,VALLE DEL CAUCA
2,11,Carlos Valderrama,True,2023-02-01,CALI,VALLE DEL CAUCA
3,12,Faustino Asprilla,True,2018-03-07,CALI,VALLE DEL CAUCA
4,13,GEOVANNY Hidalgo,True,2021-11-08,PASTO,NARIÑO
5,15,Juan Solano,True,2022-07-16,CALI,VALLE DEL CAUCA
6,16,Jan Sastre,True,2020-04-01,CALI,VALLE DEL CAUCA
7,19,Bladimir Padrino,True,None,CALI,VALLE DEL CAUCA
8,21,Vladimir Putin,True,2021-05-11,CALI,VALLE DEL CAUCA
9,31,Hector Aquiles,True,2022-09-16,CALI,VALLE DEL CAUCA
10,26,Laura Acuña,True,2020-07-16,CALI,VALLE DEL CAUCA
11,23,Andrea Guerrero,True,2019-05-13,CALI,VALLE DEL CAUCA
12,22,Jairon Montes,True,2021-07-02,CALI,VALLE DEL CAUCA
13,35,Yeison Jimenez,True,2023-05-25,CALI,VALLE DEL CAUCA
14,5,James Rodriguez,True,2015-07-01,None,None
15,9,DIEGO Maradona,True,2015-02-16,CALI,VALLE DEL CAUCA
16,18,Nicolas Maduro,True,2018-03-01,CALI,VALLE DEL CAUCA
17,6,mensajero_o,True,2023-08-01,None,None
18,29,Sebastian Acuña,True,2023-07-01,CALI,VALLE DEL CAUCA
19,2,mensajero2,True,None,None,None
20,36,LUISGIL,True,None,CALI,VALLE DEL CAUCA
21,1,mensajero1,True,None,ACOPI YUMBO,VALLE DEL CAUCA
22,45,BMAYORGA,True,None,CALI,VALLE DEL CAUCA
23,27,ALEXANDERMOSQUERA,True,2023-02-16,CALI,VALLE DEL CAUCA
24,43,ADELGADO,True,None,CALI,VALLE DEL CAUCA
25,38,YESYDVINASCO,True,2023-12-11,CALI,VALLE DEL CAUCA
26,48,JULIANVILLANUEVA,True,2024-07-12,CALI,VALLE DEL CAUCA
27,34,VICTORARARAT,True,None,CALI,VALLE DEL CAUCA
28,4,Lionel_messi,False,2018-12-17,CALI,VALLE DEL CAUCA
29,49,JSANCHEZ,True,None,None,None
30,46,YBOLANOS,True,None,CALI,VALLE DEL CAUCA
31,40,ESTEBANMUÑOZ,True,None,None,None
32,37,HENRYCARABALI,True,None,CALI,VALLE DEL CAUCA
33,33,JONATANMANZANO,True,2022-09-21,TULUA,VALLE DEL CAUCA
34,3,Biil-Gates,True,2012-05-08,CALI,VALLE DEL CAUCA
35,39,JORGEMOSQUERA,True,2021-05-10,POPAYAN,CAUCA
36,17,ALEXISLASSO,True,2022-08-01,CALI,VALLE DEL CAUCA
37,7,admin,True,None,CALI,VALLE DEL CAUCA
38,44,RVALLEJO,True,None,CALI,VALLE DEL CAUCA
39,25,ANDRESGUTIERREZ,True,2022-09-16,CALI,VALLE DEL CAUCA
40,41,LUISCARDONA,True,None,CALI,VALLE DEL CAUCA
41,30,JHONTROCHEZ,True,2022-10-01,CALI,VALLE DEL CAUCA
42,83,DANIELMAZUERA,True,2024-08-08,CALI,VALLE DEL CAUCA
43,47,HVARGAS,True,None,CALI,VALLE DEL CAUCA
44,50,MVERONICA,True,None,CALI,VALLE DEL CAUCA
45,28,JHONMUÑOZ,True,2021-05-14,CALI,VALLE DEL CAUCA
46,42,JPEDROZA,True,None,CALI,VALLE DEL CAUCA
47,84,WILSONMORALES,True,2024-08-12,CALI,VALLE DEL CAUCA
48,32,CARLOSGONZALEZ,True,2020-10-20,CALI,VALLE DEL CAUCA
49,24,JOELVILLADA,True,2022-02-21,CALI,VALLE DEL CAUCA

In [5]:
# Dimension sede (dim_sede)
cur = conn.cursor()

# nombre -> nombre_sede
cur.execute("""
    SELECT column_name
    FROM information_schema.columns
    WHERE table_name = 'sede'
    AND column_name = 'nombre';
""")
result = cur.fetchone()

if result is not None:
    cur.execute("ALTER TABLE sede RENAME COLUMN nombre TO nombre_sede")

query = ("""
    SELECT sede_id, nombre_sede, direccion, nombre_ciudad AS ciudad_sede, nombre_departamento AS departamento_sede, cliente_id FROM sede AS dim_sede
    INNER JOIN ciudad ON dim_sede.ciudad_id = ciudad.id
    INNER JOIN departamento ON ciudad.departamento_id = departamento.id
""")
df = pd.read_sql(query, conn)
# Visualizar los datos
df

C:\Users\Usuario\AppData\Local\Temp\ipykernel_17680\4149103033.py:21: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,sede_id,nombre_sede,direccion,ciudad_sede,departamento_sede,cliente_id
0,10,FARALLONES /123,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,4
1,11,REMEDIOZ/ 123,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,4
2,13,DIME / LOS ROJOS,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,4
3,14,DESPACHOS / LOS ROJOS,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,4
4,23,POPAYAN BODEGA 28 / A,Los angeles distrito Latino,POPAYAN,CAUCA,11
5,24,PASTO VITRINA /,Los angeles distrito Latino,PASTO,NARIÑO,11
6,25,PASTO BODEGA 29/,Los angeles distrito Latino,PASTO,NARIÑO,11
7,26,PALMIRA BODEGA 20 /,Los angeles distrito Latino,PALMIRA,VALLE DEL CAUCA,11
8,32,CLINICA FABILUX,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,12
9,33,FORDES PASOANCHOS,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,11
10,35,JMC /,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,11
11,46,SAN BER NANDO,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,24
12,44,VALLE NORTE,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,25
13,45,CAMBULOS,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,25
14,1,Sede principal - Cliente1,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,2
15,2,sede aux - cliente 1,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,2
16,5,VASQUEZ COBO,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,5
17,7,VILLACOLOMBIA,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,5
18,9,PRINCIPAL/ ESENSA,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,10
19,8,PRINCIPAL / OCCIDENTE,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,5
20,48,BATALLON DISPENSARIO,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,12
21,28,CONTRIBUTIVO / ESENSA,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,10
22,49,OCCISALUD,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,26
23,40,TRAUMA ORIENTE,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,9
24,6,CAPITOLIO,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,5
25,41,ARTMEDICA,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,18
26,42,CLINICA CALI,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,7
27,15,PRINCIPAL NORTE / CHINA PACIFICO,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,11
28,16,MEGATALLER / CHINA PACIFICO,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,11
29,17,BUSES Y CAMIONES -,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,11
30,18,FORCAS,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,11
31,19,HYUNDAI /,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,11
32,20,FORD CAÑAS FLASCAS,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,11
33,21,BUGA BODEGA 24,Los angeles distrito Latino,BUGA,VALLE DEL CAUCA,11
34,22,TULUA BODEGA 26 /,Los angeles distrito Latino,TULUA,VALLE DEL CAUCA,11
35,29,PROVIDA ATENCION BASICA,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,10
36,34,AUTOPISTA,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,11
37,36,PRINCIPAL /14,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,6
38,37,HEMAS,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,8
39,47,CLINICA CALI,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,7
40,51,CLUB NOEL,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,22
41,30,RIOCAUCA / ESENSA,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,10
42,50,RECUPERAR,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,15
43,38,HEMOLIFE,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,3
44,31,CRISTO REY,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,7
45,52,NUEVA HEMATO,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,8
46,53,NUEVA HEMATO,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,8
47,54,NUEVA HEMATO,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,8
48,85,CIMEX,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,27
49,3,TORRES DE MARACAIBO,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,5
50,4,INGENIO,Los angeles distrito Latino,CALI,VALLE DEL CAUCA,5
51,12,PALMA REAL / LOS ROJOS,Los angeles distrito Latino,PALMIRA,VALLE DEL CAUCA,4

In [12]:
# Dimension fecha (dim_fecha)

cur = conn.cursor()

# Se añaden las columnas dia y mes
cur.execute("""
    SELECT column_name
    FROM information_schema.columns
    WHERE table_name = 'mensajeria_estadosservicio'
    AND column_name = 'dia';
""")
result = cur.fetchone()

if result is None:
    cur.execute("ALTER TABLE mensajeria_estadosservicio ADD COLUMN dia INTEGER")

cur.execute("""
    SELECT column_name
    FROM information_schema.columns
    WHERE table_name = 'mensajeria_estadosservicio'
    AND column_name = 'mes';
""")
result = cur.fetchone()

if result is None:
    cur.execute("ALTER TABLE mensajeria_estadosservicio ADD COLUMN mes TEXT")

# Carga del dataframe
query = ("""
    SELECT id, fecha, dia, mes
    FROM mensajeria_estadosservicio AS dim_fecha
""")

df = pd.read_sql(query,conn)

# Extraccion de dia y mes a partir de la columna fecha

cur.execute("""
    UPDATE mensajeria_estadosservicio
    SET
        dia = EXTRACT(DAY FROM fecha),
        mes = EXTRACT(MONTH FROM fecha)
    WHERE dia IS NULL OR mes IS NULL;
""")

cur.execute("""
    UPDATE mensajeria_estadosservicio
    SET mes = TO_CHAR(fecha, 'TMMonth')
    WHERE mes IS NULL;
""")

conn.commit()
cur.close()

df

C:\Users\Usuario\AppData\Local\Temp\ipykernel_17680\205595281.py:34: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query,conn)

            id       fecha  dia mes
0         1014  2024-01-29   29   1
1         1484  2024-01-30   30   1
2         2829  2024-02-06    6   2
3         1888  2024-02-01    1   2
4        32312  2024-04-06    6   4
...        ...         ...  ...  ..
128397  128805  2024-08-31   31   8
128398  128806  2024-08-31   31   8
128399  128807  2024-08-31   31   8
128400  128808  2024-08-31   31   8
128401  128809  2024-08-31   31   8

[128402 rows x 4 columns]

In [14]:
# Dimension hora (dim_hora)
cur = conn.cursor()

query = ("""
    SELECT id, hora FROM mensajeria_estadosservicio AS dim_hora
""")

df = pd.read_sql(query,conn)

df

C:\Users\Usuario\AppData\Local\Temp\ipykernel_17680\2371783093.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query,conn)

            id      hora
0         1014  01:13:32
1         1484  18:45:12
2         2829  11:34:04
3         1888  14:50:39
4        32312  16:11:21
...        ...       ...
128397  128805  15:01:03
128398  128806  15:03:42
128399  128807  15:04:26
128400  128808  15:13:47
128401  128809  15:22:35

[128402 rows x 2 columns]

In [9]:
conn.rollback()