In [2]:
!pip install python-dotenv

Collecting python-dotenv
  Downloading python_dotenv-1.1.0-py3-none-any.whl.metadata (24 kB)
Downloading python_dotenv-1.1.0-py3-none-any.whl (20 kB)
Installing collected packages: python-dotenv
Successfully installed python-dotenv-1.1.0

In [3]:
import os
import pandas as pd
import numpy as np
import psycopg2
from dotenv import load_dotenv

In [4]:
# Cargar las variables de entorno
load_dotenv()

#Obtener las variables
user = os.getenv("DB_USER")
password = os.getenv("DB_PASSWORD")
host = os.getenv("DB_HOST")
port = os.getenv("DB_PORT")
dbname = os.getenv("DB_NAME")

#Conectarse a la base de datos
conn = psycopg2.connect(
    dbname = dbname,
    user = user,
    password = password,
    host = host,
)

In [7]:
# Creación de los DataFrame a partir de consultas

# Sede
query = "SELECT * FROM sede"
df = pd.read_sql(query, conn)
# Visualizar los datos
df.head(5)

C:\Users\Usuario\AppData\Local\Temp\ipykernel_19560\1847472227.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,sede_id,nombre,direccion,telefono,nombre_contacto,ciudad_id,cliente_id
0,10,FARALLONES /123,Los angeles distrito Latino,310-70000,JUAN PEREZ,1,4
1,11,REMEDIOZ/ 123,Los angeles distrito Latino,310-70000,JUAN PEREZ,1,4
2,13,DIME / LOS ROJOS,Los angeles distrito Latino,310-70000,JUAN PEREZ,1,4
3,14,DESPACHOS / LOS ROJOS,Los angeles distrito Latino,310-70000,JUAN PEREZ,1,4
4,23,POPAYAN BODEGA 28 / A,Los angeles distrito Latino,310-70000,JUAN PEREZ,3,11
5,24,PASTO VITRINA /,Los angeles distrito Latino,310-70000,JUAN PEREZ,4,11
6,25,PASTO BODEGA 29/,Los angeles distrito Latino,310-70000,JUAN PEREZ,4,11
7,26,PALMIRA BODEGA 20 /,Los angeles distrito Latino,310-70000,JUAN PEREZ,2,11
8,32,CLINICA FABILUX,Los angeles distrito Latino,310-70000,JUAN PEREZ,1,12
9,33,FORDES PASOANCHOS,Los angeles distrito Latino,310-70000,JUAN PEREZ,1,11

In [8]:
# Cliente
query = "SELECT * FROM cliente"
df = pd.read_sql(query, conn)
df.head(5)

C:\Users\Usuario\AppData\Local\Temp\ipykernel_19560\2386653142.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,cliente_id,nit_cliente,nombre,email,direccion,telefono,nombre_contacto,ciudad_id,tipo_cliente_id,activo,coordinador_id,sector
0,1,25,Cliente 2,algo.com,Calle 100 No 25-18,327-00000,Cristiano Ronaldo,1,1,True,NaN,S
1,2,123,Cliente 1,algo.com,Calle 100 No 25-18,327-00000,Cristiano Ronaldo,1,1,True,2.0,industrial
2,6,24390-3,CLINICA DEPORTIVA DEL SUR,algo.com,Calle 100 No 25-18,327-00000,Cristiano Ronaldo,1,1,True,1.0,salud
3,19,8301821,HOSPITAL ORTOPEDICO DE COLOMBIA,algo.com,Calle 100 No 25-18,327-00000,Cristiano Ronaldo,1,1,True,NaN,salud
4,8,5017350-8,CLINICA NEFROLOGOS DE CALI,algo.com,Calle 100 No 25-18,327-00000,Cristiano Ronaldo,1,1,True,NaN,salud

In [9]:
# Mensajero
query = "SELECT * FROM mensajero"
df = pd.read_sql(query, conn)
df.head(5)

C:\Users\Usuario\AppData\Local\Temp\ipykernel_19560\1694129294.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

DatabaseError: Execution failed on sql 'SELECT * FROM mensajero': no existe la relación «mensajero»
LINE 1: SELECT * FROM mensajero
                      ^