In [2]:
!pip install python-dotenv

Requirement already satisfied: python-dotenv in c:\users\usuario\appdata\local\programs\python\python312\lib\site-packages (1.1.0)

In [3]:
import os
import pandas as pd
import numpy as np
import psycopg2
from dotenv import load_dotenv

In [4]:
# Cargar las variables de entorno
load_dotenv()

#Obtener las variables
user = os.getenv("DB_USER")
password = os.getenv("DB_PASSWORD")
host = os.getenv("DB_HOST")
port = os.getenv("DB_PORT")
dbname = os.getenv("DB_NAME")

#Conectarse a la base de datos
conn = psycopg2.connect(
    dbname = dbname,
    user = user,
    password = password,
    host = host,
)

In [157]:
# Modificaciones a la tabla ciudad

# Creacion del cursor
cur = conn.cursor()

# Ejecucion de los ALTER TABLE por separado
cur.execute("ALTER TABLE ciudad RENAME COLUMN ciudad_id TO id")
cur.execute("ALTER TABLE ciudad RENAME COLUMN nombre TO nombre_ciudad")

# Confirmacion de los cambios
conn.commit()

# Cierre del cursor
cur.close()

query = ("SELECT * FROM ciudad;")
df = pd.read_sql(query, conn)
df

C:\Users\Usuario\AppData\Local\Temp\ipykernel_29700\448687141.py:17: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

   id nombre_ciudad  departamento_id
0   6          BUGA                1
1   5        BOGOTA                2
2   4         PASTO                4
3   3       POPAYAN                3
4   2       PALMIRA                1

In [186]:
# Modificaciones a la tabla departamento

# Creacion del cursor
cur = conn.cursor()

# Ejecucion de los ALTER TABLE por separado
cur.execute("ALTER TABLE departamento RENAME COLUMN departamento_id TO id")
cur.execute("ALTER TABLE departamento RENAME COLUMN nombre TO nombre_departamento")

# Confirmacion de los cambios
conn.commit()

# Cierre del cursor
cur.close()

query = ("SELECT * FROM departamento;")
df = pd.read_sql(query, conn)
df

UndefinedColumn: no existe la columna «departamento_id»

In [185]:
# Union de las tablas ciudad y departamento
query = ("SELECT ciudad.id, nombre_ciudad, nombre_departamento FROM ciudad "
         "INNER JOIN departamento ON departamento.id = ciudad.departamento_id")
df = pd.read_sql(query, conn)
df

C:\Users\Usuario\AppData\Local\Temp\ipykernel_29700\3288094744.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

    id  nombre_ciudad nombre_departamento
0    6           BUGA     VALLE DEL CAUCA
1    5         BOGOTA        CUNDINAMARCA
2    4          PASTO              NARIÑO
3    3        POPAYAN               CAUCA
4    2        PALMIRA     VALLE DEL CAUCA
5    1           CALI     VALLE DEL CAUCA
6    7          TULUA     VALLE DEL CAUCA
7   10        GUACARI     VALLE DEL CAUCA
8   11     CANDELARIA     VALLE DEL CAUCA
9   12        CARTAGO     VALLE DEL CAUCA
10   9        JAMUNDI     VALLE DEL CAUCA
11   8          YUMBO     VALLE DEL CAUCA
12  13    ACOPI YUMBO     VALLE DEL CAUCA
13  14   CENCAR YUMBO     VALLE DEL CAUCA
14  15         ZARZAL     VALLE DEL CAUCA
15  16     VILLA RICA               CAUCA
16  17        FLORIDA     VALLE DEL CAUCA
17  18        PRADERA     VALLE DEL CAUCA
18  19  CALIMA DARIEN     VALLE DEL CAUCA

In [5]:
# Creación de los DataFrame a partir de consultas

# Sede
query = "SELECT * FROM sede"
df = pd.read_sql(query, conn)
# Visualizar los datos
df.head(5)

C:\Users\Usuario\AppData\Local\Temp\ipykernel_29700\3937428837.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,sede_id,nombre,direccion,telefono,nombre_contacto,ciudad_id,cliente_id
0,10,FARALLONES /123,Los angeles distrito Latino,310-70000,JUAN PEREZ,1,4
1,11,REMEDIOZ/ 123,Los angeles distrito Latino,310-70000,JUAN PEREZ,1,4
2,13,DIME / LOS ROJOS,Los angeles distrito Latino,310-70000,JUAN PEREZ,1,4
3,14,DESPACHOS / LOS ROJOS,Los angeles distrito Latino,310-70000,JUAN PEREZ,1,4
4,23,POPAYAN BODEGA 28 / A,Los angeles distrito Latino,310-70000,JUAN PEREZ,3,11

In [184]:
# Cliente

# Creacion del cursor
cur = conn.cursor()

cur.execute("ALTER TABLE cliente RENAME COLUMN nombre TO nombre_cliente")

# Confirmacion de los cambios
conn.commit()

# Cierre del cursor
cur.close()

query = (
    "SELECT cliente_id, nit_cliente, nombre_cliente, nombre_ciudad, nombre_departamento, sector, activo "
    "FROM cliente AS dim_cliente "
    "INNER JOIN ciudad ON dim_cliente.ciudad_id = ciudad.id "
    "INNER JOIN departamento ON ciudad.departamento_id = departamento.id"
)

df = pd.read_sql(query, conn)
df

C:\Users\Usuario\AppData\Local\Temp\ipykernel_29700\572040111.py:21: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,cliente_id,nit_cliente,nombre_cliente,nombre_ciudad,nombre_departamento,sector,activo
0,1,25,Cliente 2,CALI,VALLE DEL CAUCA,S,True
1,2,123,Cliente 1,CALI,VALLE DEL CAUCA,industrial,True
2,6,24390-3,CLINICA DEPORTIVA DEL SUR,CALI,VALLE DEL CAUCA,salud,True
3,19,8301821,HOSPITAL ORTOPEDICO DE COLOMBIA,CALI,VALLE DEL CAUCA,salud,True
4,8,5017350-8,CLINICA NEFROLOGOS DE CALI,CALI,VALLE DEL CAUCA,salud,True
5,3,312289-5,BANCO REGIONAL DE SANGRE BLOD-LIFE,CALI,VALLE DEL CAUCA,salud,True
6,4,306215-0,CRUZ AZUL-LIFE,CALI,VALLE DEL CAUCA,salud,True
7,5,300513-3,CLINICA CALI -JOVEN,CALI,VALLE DEL CAUCA,salud,True
8,7,951033-8,CLINICA COFFE -HEALTH,CALI,VALLE DEL CAUCA,salud,True
9,9,149757-6,UNIDAD DE TRAUMA DEL OESTE,CALI,VALLE DEL CAUCA,salud,True
10,10,550254-8,CLINICA VIDA Y SALUD,CALI,VALLE DEL CAUCA,salud,True
11,11,327282-4,CARROS DEL PACIFICO (CHINA),CALI,VALLE DEL CAUCA,industrial,True
12,12,242742-,CLINICA DEL SUR DE CALI,CALI,VALLE DEL CAUCA,salud,True
13,13,616935,DISTRIBUCIONES MEDICOS RAPIDOS,CALI,VALLE DEL CAUCA,salud,True
14,14,908245,UNIDAD MEDICA SANTA MARIA,CALI,VALLE DEL CAUCA,S,True
15,15,800000,CENTRO RECUPERARSE,CALI,VALLE DEL CAUCA,salud,True
16,16,0056330,CARROS RAPIDOS DE CALI,CALI,VALLE DEL CAUCA,industrial,True
17,17,78948,CLINICA LOS CONDORES,CALI,VALLE DEL CAUCA,salud,True
18,18,9051024,UNIDAD MEDICA ESTELAR,CALI,VALLE DEL CAUCA,S,True
19,20,8000569,AUTOS-RAPIDOS,YUMBO,VALLE DEL CAUCA,industrial,True
20,21,900248,SALUD DE OCCIDENTE,CALI,VALLE DEL CAUCA,S,True
21,22,8999020,FUNDACION CLINICA INFANTIL LOS GRITONES,CALI,VALLE DEL CAUCA,S,True
22,23,900603,CLINICA MEDICA S.A.S,CALI,VALLE DEL CAUCA,salud,True
23,24,9009754,CLINICA SAN RAFAEL DE OCCIDENTE,CALI,VALLE DEL CAUCA,salud,True
24,25,900361,CALI SULUD Y VIDA,CALI,VALLE DEL CAUCA,salud,True
25,26,25478,OCCIDENTE DE SALUD-CALI,CALI,VALLE DEL CAUCA,salud,True
26,27,201478,MEDICOS Y SALUD,CALI,VALLE DEL CAUCA,industrial,True

In [112]:
# Mensajero
query = "SELECT * FROM mensajero"
df = pd.read_sql(query, conn)
df.head(5)

C:\Users\Usuario\AppData\Local\Temp\ipykernel_29700\1694129294.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

DatabaseError: Execution failed on sql 'SELECT * FROM mensajero': no existe la relación «mensajero»
LINE 1: SELECT * FROM mensajero
                      ^